;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-brace
        c-electric-colon
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-indent-line-or-region
        comment-or-uncomment-region
        indent-for-tab-command
        kill-region
        mouse-set-region
        overwrite-mode
        switch-to-next-buffer
        upcase-region
        xref-find-definitions
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-pound
        ))
